Repository Fitting-Pair/FrontEnd, pull requests merged in 2024-08, with the labels that each got.

#41 [Feat] feature/#40 회원가입 및 로그인 ui 수정
  fitting-pair/src/components/Button/Submit.style.js
  fitting-pair/src/util/validate.js
Labels: STYLE

#27 Swiper & QR Genrator
  fitting-pair/package.json
  fitting-pair/public/images/top.png
  fitting-pair/src/components/ApparelComponent/ApparelComponent.jsx
  fitting-pair/src/components/Icon/Icon.style.js
  fitting-pair/src/components/PersonalCloth/PersonalCloth.jsx
  fitting-pair/src/components/PersonalCloth/PersonalCloth.style.js
  fitting-pair/src/components/QRCodeGenerator/QRCodeGenerator.jsx
  fitting-pair/src/components/QRCodeGenerator/QRCodeGenerator.style.js
  fitting-pair/src/components/ResultPaper/ResultPaper.jsx
  fitting-pair/src/components/SwiperComponent/SwiperComponent.jsx
  fitting-pair/src/components/index.js
  fitting-pair/src/constants/apparel.js
  fitting-pair/src/pages/Result/ResultPage.css
  fitting-pair/src/pages/Result/ResultPage.jsx
  fitting-pair/src/pages/Result/ResultPage.style.js
  fitting-pair/src/pages/Styling/StylingPage.jsx
  fitting-pair/src/pages/Styling/StylingPage.style.js
  fitting-pair/yarn.lock
Labels: FEAT

#43 [Feat] feature/#42 자동 input 확대 수정 & 아이콘 수정
  fitting-pair/index.html
  fitting-pair/public/images/logo.svg
  fitting-pair/src/components/Button/Submit.style.js
  fitting-pair/src/pages/Home/Homepage.style.js
Labels: FEAT

#45 [Feat] feature/#38 이미지 api 연결
  fitting-pair/package.json
  fitting-pair/src/App.jsx
  fitting-pair/src/api/index.js
  fitting-pair/src/api/result.js
  fitting-pair/src/components/Webcam/Webcam.jsx
  fitting-pair/src/constants/key.js
  fitting-pair/src/constants/path.js
  fitting-pair/src/hooks/queries/images/usePostImg.js
  fitting-pair/src/hooks/queries/results/useGetBodyCheckResult.js
  fitting-pair/src/pages/BodyCheck/BodyCheckPage.jsx
  fitting-pair/src/pages/BodyCheck/BodyCheckPage.style.js
  fitting-pair/src/pages/Result/ResultPage.jsx
  fitting-pair/src/store/useLoadingStore.js
  fitting-pair/yarn.lock
Labels: FEAT

#46 [Sytle] style/#44 배경 선 추가
  fitting-pair/src/assets/images/Vector.svg
  fitting-pair/src/layout/FittingLayout/FittingLayout.jsx
  fitting-pair/src/layout/FittingLayout/FittingLayout.style.js
Labels: STYLE

#48 [Feat] feature/#47 로그인 회원가입 로딩처리 추가 & 결과지 오류 처리 추가
  fitting-pair/src/components/Loading/Loading.jsx
  fitting-pair/src/components/Loading/Loading.style.js
  fitting-pair/src/components/common/error/Error.jsx
  fitting-pair/src/components/common/error/Error.style.js
  fitting-pair/src/components/index.js
  fitting-pair/src/pages/Login/LoginPage.jsx
  fitting-pair/src/pages/Result/ResultPage.jsx
  fitting-pair/src/pages/SignUp/SignUpPage.jsx
Labels: FEAT

#52 [Feat] feature/#51 마이페이지 api 연결
  fitting-pair/src/App.jsx
  fitting-pair/src/api/user.js
  fitting-pair/src/components/ResultPaper/ResultPaper.jsx
  fitting-pair/src/components/ResultPaper/ResultPaper.style.js
  fitting-pair/src/constants/key.js
  fitting-pair/src/constants/path.js
  fitting-pair/src/hooks/queries/results/useGetAllResult.js
  fitting-pair/src/hooks/queries/useLogout.js
  fitting-pair/src/pages/MyPage/MyPage.jsx
  fitting-pair/src/pages/MyPage/MyPage.style.js
  fitting-pair/src/pages/Result/Mobile/Detail/ResultDetail.jsx
  fitting-pair/src/pages/Result/Mobile/Detail/ResultDetail.style.js
  fitting-pair/src/pages/Result/Mobile/MoblieResultPage.jsx
  fitting-pair/src/pages/Result/Mobile/MoblieResultPage.style.js
Labels: ✨ feat
